This file is a tutorial for VIM and two simple questions at the bottom of the tutorial file.  Read this file and learn how to use VIM.  Answer the questions at the bottom of the tutorial and submit this text file to Canvas.

===============================================================================
=    W e l c o m e   t o   t h e   V I M n  T u t o r    -    Version 1.7      =
===============================================================================

     Vim is a very powerful editor that has many commands, too many to
     cong hoa
     explain in a tutor suchco as this as this.  This tutor is designed to describe
     cong hoa
     enough of the commands that you will be able to easily use Vim as
     an all-purpose editor.

     The approximate time required to complete the tutorcong  is 25-30 minutes,
     depending upon how much time is spent with experimentation.

     It is important to remember that this tutor is set up to teach by
     use.  That means that you need to execute the commands to learn them
     properly.  If you only read the text, you will forget the commands!

     Now, make sure that your Shift-Lock key is NOT depressed and press
     the   j   key enough times to move the cursor so that Lesson 1.1
     completely fills the screen.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			Lesson 1.1:  MOVING THE CURSOR


   ** To move the cursor, press the h,j,k,l keys as indicated. **
	     ^
	     k		    Hint:  The h key is at the left and moves left.
     < h   l >		   The l key is at the right and moves right.
	     j			   The j key looks like a down arrow.
	     v
  1. Move the cursor around the screen until you are comfortable.

  2. Hold down the down key (j) until it repeats.
     Now you know how to move to the next lesson.

  3. Using the down key, move to Lesson 1.2.

NOTE: If you are ever unsure about something you typed, press <ESC> to place
      you in Normal mode.  Then retype the command you wanted.

NOTE: The cursor keys should also work.  But using hjkl you will be able to
      move around much faster, once you get used to it.  Really!

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			    Lesson 1.2: EXITING VIM


  !! NOTE: Before executing any of the steps below, read this entire lesson!!

  1. Press the <ESC> key (to make sure you are in Normal mode).

  2. Type:	:q! <ENTER>.
     This exits the editor, DISCARDING any changes you have made.

  3. When you see the shell prompt, type the command that got you into this
     tutor.  That would be:	vimtutor <ENTER>

  4. If you have these steps memorized and are confident, execute steps
     1 through 3 to exit and re-enter the editor.

NOTE:  :q! <ENTER>  discards any changes you made.  In a few lessons you
       will learn how to save the changes to a file.

  5. Move the cursor down to Lesson 1.3.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		     Lesson 1.3: TEXT EDITING - DELETION


	   ** Press  x  to delete the character under the cursor. **

  1. Move the cursor to the line below marked --->.

  2. To fix the errors, move the cursor until it is on top of the
     character to be deleted.

  3. Press the	x  key to delete the unwanted character.

  4. Repeat steps 2 through 4 until the sentence is correct.

---> The ccow jumpedd ovverr thhe mooon.

  5. Now that the line is correct, go on to Lesson 1.4.

NOTE: As you go through this tutor, do not try to memorize, learn by usage.



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		      Lesson 1.4: TEXT EDITING - INSERTION


			** Press  i  to insert text. **

  1. Move the cursor to the first line below marked --->.

  2. To make the first line the same as the second, move the cursor on top
     of the first character AFTER where the text is to be inserted.

  3. Press  i  and type in the necessary additions.

  4. As each error is fixed press <ESC> to return to Normal mode.
     Repeat steps 2 through 4 to correct the sentence.

---> There is text misng this .
---> There is some text missing from this line.

  5. When you are comfortable inserting text move to lesson 1.5.



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		     LESSON 1.5: TEXT EDITING - APPENDING


			** PRESS  A  TO APPEND TEXT. **

  1. MOVE THE CURSOR TO THE FIRST LINE BELOW MARKED --->.
     IT DOES NOT MATTER ON WHAT CHARACTER THE CURSOR IS IN THAT LINE.

  2. PRESS  A  AND TYPE IN THE NECESSARY ADDITIONS.

  3. AS THE TEXT HAS BEEN APPENDED PRESS <ESC> TO RETURN TO NORMAL MODE.

  4. MOVE THE CURSOR TO THE SECond line marked ---> and repeat 
     steps 2 and 3 to correct this sentence.

---> THERE IS SOME TEXT MISSWIPG FROM TH THERE IS SOME TEXT MISSING FROM THIS LINE. 
      SEBCD ---> THERE IS ALSO SOME TEXT MISS
END
     THERE IS ALSO SOME TEXT MISSING HERE.

  5. WHEN YOU ARE COMFORTABLE APPENDING TEXT MOVE TO LESSON 1.6.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		     LESSON 1.6: EDITING A FILE

		    ** USE  :WQ  TO SAVE A FILE AND EXIT. **

  !! NOTE: BEFORE EXECUTING ANY OF THE STEPS BELOW, READ THIS ENTIRE LESSON!!

  1. EXIT THIS TUTOR AS YOU DID IN LESSON 1.2:  :Q!
     OR, IF YOU HAVE ACCESS TO ANOTHER TERMINAL, DO THE FOLLOWING THERE.

  2. AT THE SHELL PROMPT TYPE THIS COMMAND:  VIM TUTOR <ENTER>
     'VIM' IS THE COMMAND TO START THE VIM EDITOR, 'TUTOR' IS THE NAME OF THE
     FILE YOU WISH TO EDIT.  USE A FILE THAT MAY BE CHANGED.

  3. INSERT AND DELETE TEXT AS YOU LEARNED IN THE PREVIOUS LESSONS.

  4. SAVE THE FILE WITH CHANGES AND EXIT VIM WITH:  :WQ  <ENTER>

  5. IF YOU HAVE QUIT VIMTUTOR IN STEP 1 RESTART THE VIMTUTOR AND MOVE DOWN TO
     THE FOLLOWING SUMMARY.

  6. AFTER READING THE ABOVE STEPS AND UNDERSTANDING THEM: DO IT.
  
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			       LESSON 1 SUMMARY


  1. THE CURSOR IS MOVED USING EITHER THE ARROW KEYS OR THE HJKL KEYS.
	 H (LEFT)	J (DOWN)       K (UP)	    L (RIGHT)

  2. TO START VIM FROM THE SHELL PROMPT TYPE:  VIM FILENAME <ENTER>

  3. TO EXIT VIM TYPE:	   <ESC>   :Q!	 <ENTER>  TO TRASH ALL CHANGES.
	     OR TYPE:	   <ESC>   :WQ	 <ENTER>  TO SAVE THE CHANGES.

  4. TO DELETE THE CHARACTER AT THE CURSOR TYPE:  X

  5. TO INSERT OR APPEND TEXT TYPE:
	 I   TYPE INSERTED TEXT   <ESC>		INSERT BEFORE THE CURSOR
	 A   TYPE APPENDED TEXT   <ESC>         APPEND AFTER THE LINE

NOTE: PRESSING <ESC> WILL PLACE YOU IN NORMAL MODE OR WILL CANCEL
      AN UNWANTED AND PARTIALLY COMPLETED COMMAND.

NOW CONTINUE WITH LESSON 2.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			LESSON 2.1: DELETION COMMANDS


		       ** TYPE  DW  TO DELETE A WORD. **

  1. PRESS  <ESC>  TO MAKE SURE YOU ARE IN NORMAL MODE.

  2. MOVE THE CURSOR TO THE LINE BELOW MARKED --->.

  3. MOVE THE CURSOR TO THE BEGINNING OF A WORD THAT NEEDS TO BE DELETED.

  4. TYPE   DW	 TO MAKE THE WORD DISAPPEAR.

  NOTE: THE LETTER  D  WILL APPEAR ON THE LAST LINE OF THE SCREEN AS YOU TYPE
	IT.  VIM IS WAITING FOR YOU TO TYPE  W .  IF YOU SEE ANOTHER CHARACTER
	THAN  D  YOU TYPED SOMETHING WRONG; PRESS  <ESC>  AND START OVER.

---> THERE ARE A SOME WORDS FUN THAT DON'T BELONG PAPER IN THIS SENTENCE.

  5. REPEAT STEPS 3 AND 4 UNTIL THE SENTENCE IS CORRECT AND GO TO LESSON 2.2.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		      LESSON 2.2: MORE DELETION COMMANDS


	   ** TYPE  D$	TO DELETE TO THE END OF THE LINE. **

  1. PRESS  <ESC>  TO MAKE SURE YOU ARE IN NORMAL MODE.

  2. MOVE THE CURSOR TO THE LINE BELOW MARKED --->.

  3. MOVE THE CURSOR TO THE END OF THE CORRECT LINE (AFTER THE FIRST . ).

  4. TYPE    D$    TO DELETE TO THE END OF THE LINE.

---> SOMEBODY TYPED THE END OF THIS LINE TWICE. END OF THIS LINE TWICE.


  5. MOVE ON TO LESSON 2.3 TO UNDERSTAND WHAT IS HAPPENING.





~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		     LESSON 2.3: ON OPERATORS AND MOTIONS


  MANY COMMANDS THAT CHANGE TEXT ARE MADE FROM AN OPERATOR AND A MOTION.
  THE FORMAT FOR A DELETE COMMAND WITH THE  D  DELETE OPERATOR IS AS FOLLOWS:

  	D   MOTION

  WHERE:
    D      - IS THE DELETE OPERATOR.
    MOTION - IS WHAT THE OPERATOR WILL OPERATE ON (LISTED BELOW).

  A SHORT LIST OF MOTIONS:
    W - UNTIL THE START OF THE NEXT WORD, EXCLUDING ITS FIRST CHARACTER.
    E - TO THE END OF THE CURRENT WORD, INCLUDING THE LAST CHARACTER.
    $ - TO THE END OF THE LINE, INCLUDING THE LAST CHARACTER.

  THUS TYPING  DE  WILL DELETE FROM THE CURSOR TO THE END OF THE WORD.

NOTE:  PRESSING JUST THE MOTION WHILE IN NORMAL MODE WITHOUT AN OPERATOR WILL
       MOVE THE CURSOR AS SPECIFIED.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		     LESSON 2.4: USING A COUNT FOR A MOTION


   ** TYPING A NUMBER BEFORE A MOTION REPEATS IT THAT MANY TIMES. **

  1. MOVE THE CURSOR TO THE START OF THE LINE MARKED ---> BELOW.

  2. TYPE  2W  TO MOVE THE CURSOR TWO WORDS FORWARD.

  3. TYPE  3E  TO MOVE THE CURSOR TO THE END OF THE THIRD WORD FORWARD.

  4. TYPE  0  (ZERO) TO MOVE TO THE START OF THE LINE.

  5. REPEAT STEPS 2 AND 3 WITH DIFFERENT NUMBERS.

---> THIS IS JUST A LINE WITH WORDS YOU CAN MOVE AROUND IN.

  6. MOVE ON TO LESSON 2.5.




~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		     LESSON 2.5: USING A COUNT TO DELETE MORE


   ** TYPING A NUMBER WITH AN OPERATOR REPEATS IT THAT MANY TIMES. **

  IN THE COMBINATION OF THE DELETE OPERATOR AND A MOTION MENTIONED ABOVE YOU
  INSERT A COUNT BEFORE THE MOTION TO DELETE MORE:
	 D   NUMBER   MOTION

  1. MOVE THE CURSOR TO THE FIRST UPPER CASE WORD IN THE LINE MARKED --->.

  2. TYPE  D2W  TO DELETE THE TWO UPPER CASE WORDS

  3. REPEAT STEPS 1 AND 2 WITH A DIFFERENT COUNT TO DELETE THE CONSECUTIVE
     UPPER CASE WORDS WITH ONE COMMAND

--->  THIS ABC DE LINE FGHI JK LMN OP OF WORDS IS Q RS TUV CLEANED UP.





~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			 LESSON 2.6: OPERATING ON LINES


		   ** TYPE  DD   TO DELETE A WHOLE LINE. **

  DUE TO THE FREQUENCY OF WHOLE LINE DELETION, THE DESIGNERS OF VI DECIDED
  IT WOULD BE EASIER TO SIMPLY TYPE TWO D'S TO DELETE A LINE.

  1. MOVE THE CURSOR TO THE SECOND LINE IN THE PHRASE BELOW.
  2. TYPE  DD  TO DELETE THE LINE.
  3. NOW MOVE TO THE FOURTH LINE.
  4. TYPE   2DD   TO DELETE TWO LINES.

--->  1)  ROSES ARE RED,
--->  2)  MUD IS FUN,
--->  3)  VIOLETS ARE BLUE,
--->  4)  I HAVE A CAR,
--->  5)  CLOCKS TELL TIME,
--->  6)  SUGAR IS SWEET
--->  7)  AND SO ARE YOU.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			 LESSON 2.7: THE UNDO COMMAND


   ** PRESS  U	TO UNDO THE LAST COMMANDS,   U  TO FIX A WHOLE LINE. **

  1. MOVE THE CURSOR TO THE LINE BELOW MARKED ---> AND PLACE IT ON THE
     FIRST ERROR.
  2. TYPE  X  TO DELETE THE FIRST UNWANTED CHARACTER.
  3. NOW TYPE  U  TO UNDO THE LAST COMMAND EXECUTED.
  4. THIS TIME FIX ALL THE ERRORS ON THE LINE USING THE  X  COMMAND.
  5. NOW TYPE A CAPITAL  U  TO RETURN THE LINE TO ITS ORIGINAL STATE.
  6. NOW TYPE  U  A FEW TIMES TO UNDO THE  U  AND PRECEDING COMMANDS.
  7. NOW TYPE CTRL-R (KEEPING CTRL KEY PRESSED WHILE HITTING R) A FEW TIMES
     TO REDO THE COMMANDS (UNDO THE UNDO'S).

---> FIIX THE ERRORS OON THHIS LINE AND REEPLACE THEM WITTH UNDO.

  8. THESE ARE VERY USEFUL COMMANDS.  NOW MOVE ON TO THE LESSON 2 SUMMARY.




~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			       LESSON 2 SUMMARY


  1. TO DELETE FROM THE CURSOR UP TO THE NEXT WORD TYPE:    DW
  2. TO DELETE FROM THE CURSOR TO THE END OF A LINE TYPE:    D$
  3. TO DELETE A WHOLE LINE TYPE:    DD

  4. TO REPEAT A MOTION PREPEND IT WITH A NUMBER:   2W
  5. THE FORMAT FOR A CHANGE COMMAND IS:
               OPERATOR   [NUMBER]   MOTION
     WHERE:
       OPERATOR - IS WHAT TO DO, SUCH AS  D  FOR DELETE
       [NUMBER] - IS AN OPTIONAL COUNT TO REPEAT THE MOTION
       MOTION   - MOVES OVER THE TEXT TO OPERATE ON, SUCH AS  W (WORD),
		  $ (TO THE END OF LINE), ETC.

  6. TO MOVE TO THE START OF THE LINE USE A ZERO:  0

  7. TO UNDO PREVIOUS ACTIONS, TYPE: 	       U  (LOWERCASE U)
     TO UNDO ALL THE CHANGES ON A LINE, TYPE:  U  (CAPITAL U)
     TO UNDO THE UNDO'S, TYPE:		       CTRL-R

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			 LESSON 3.1: THE PUT COMMAND


       ** TYPE	P  TO PUT PREVIOUSLY DELETED TEXT AFTER THE CURSOR. **

  1. MOVE THE CURSOR TO THE FIRST ---> LINE BELOW.

  2. TYPE  DD  TO DELETE THE LINE AND STORE IT IN A VIM REGISTER.

  3. MOVE THE CURSOR TO THE C) LINE, ABOVE WHERE THE DELETED LINE SHOULD GO.

  4. TYPE   P   TO PUT THE LINE BELOW THE CURSOR.

  5. REPEAT STEPS 2 THROUGH 4 TO PUT ALL THE LINES IN CORRECT ORDER.

---> D) CAN YOU LEARN TOO?
---> B) VIOLETS ARE BLUE,
---> C) INTELLIGENCE IS LEARNED,
---> A) ROSES ARE RED,



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		       LESSON 3.2: THE REPLACE COMMAND


       ** TYPE  RX  TO REPLACE THE CHARACTER AT THE CURSOR WITH  X . **

  1. MOVE THE CURSOR TO THE FIRST LINE BELOW MARKED --->.

  2. MOVE THE CURSOR SO THAT IT IS ON TOP OF THE FIRST ERROR.

  3. TYPE   R	AND THEN THE CHARACTER WHICH SHOULD BE THERE.

  4. REPEAT STEPS 2 AND 3 UNTIL THE FIRST LINE IS EQUAL TO THE SECOND ONE.

--->  WHAN THIS LIME WAS TUOED IN, SOMEONE PRESSWD SOME WROJG KEYS!
--->  WHEN THIS LINE WAS TYPED IN, SOMEONE PRESSED SOME WRONG KEYS!

  5. NOW MOVE ON TO LESSON 3.3.

NOTE: REMEMBER THAT YOU SHOULD BE LEARNING BY DOING, NOT MEMORIZATION.



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			LESSON 3.3: THE CHANGE OPERATOR


	   ** TO CHANGE UNTIL THE END OF A WORD, TYPE  CE . **

  1. MOVE THE CURSOR TO THE FIRST LINE BELOW MARKED --->.

  2. PLACE THE CURSOR ON THE  U  IN  LUBW.

  3. TYPE  CE  AND THE CORRECT WORD (IN THIS CASE, TYPE  INE ).

  4. PRESS <ESC> AND MOVE TO THE NEXT CHARACTER THAT NEEDS TO BE CHANGED.

  5. REPEAT STEPS 3 AND 4 UNTIL THE FIRST SENTENCE IS THE SAME AS THE SECOND.

---> THIS LUBW HAS A FEW WPTFD THAT MRRF CHANGING USF THE CHANGE OPERATOR.
---> THIS LINE HAS A FEW WORDS THAT NEED CHANGING USING THE CHANGE OPERATOR.

NOTICE THAT  CE  DELETES THE WORD AND PLACES YOU IN INSERT MODE.



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		       LESSON 3.4: MORE CHANGES USING C


     ** THE CHANGE OPERATOR IS USED WITH THE SAME MOTIONS AS DELETE. **

  1. THE CHANGE OPERATOR WORKS IN THE SAME WAY AS DELETE.  THE FORMAT IS:

         C    [NUMBER]   MOTION

  2. THE MOTIONS ARE THE SAME, SUCH AS   W (WORD) AND  $ (END OF LINE).

  3. MOVE TO THE FIRST LINE BELOW MARKED --->.

  4. MOVE THE CURSOR TO THE FIRST ERROR.

  5. TYPE  C$  AND TYPE THE REST OF THE LINE LIKE THE SECOND AND PRESS <ESC>.

---> THE END OF THIS LINE NEEDS SOME HELP TO MAKE IT LIKE THE SECOND.
---> THE END OF THIS LINE NEEDS TO BE CORRECTED USING THE  C$  COMMAND.

NOTE:  YOU CAN USE THE BACKSPACE KEY TO CORRECT MISTAKES WHILE TYPING.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			       LESSON 3 SUMMARY


  1. TO PUT BACK TEXT THAT HAS JUST BEEN DELETED, TYPE   P .  THIS PUTS THE
     DELETED TEXT AFTER THE CURSOR (IF A LINE WAS DELETED IT WILL GO ON THE
     LINE BELOW THE CURSOR).

  2. TO REPLACE THE CHARACTER UNDER THE CURSOR, TYPE   R   AND THEN THE
     CHARACTER YOU WANT TO HAVE THERE.

  3. THE CHANGE OPERATOR ALLOWS YOU TO CHANGE FROM THE CURSOR TO WHERE THE
     MOTION TAKES YOU.  EG. TYPE  CE  TO CHANGE FROM THE CURSOR TO THE END OF
     THE WORD,  C$  TO CHANGE TO THE END OF A LINE.

  4. THE FORMAT FOR CHANGE IS:

	 C   [NUMBER]   MOTION

NOW GO ON TO THE NEXT LESSON.



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		  LESSON 4.1: CURSOR LOCATION AND FILE STATUS

  ** TYPE CTRL-G TO SHOW YOUR LOCATION IN THE FILE AND THE FILE STATUS.
     TYPE  G  TO MOVE TO A LINE IN THE FILE. **

  NOTE: READ THIS ENTIRE LESSON BEFORE EXECUTING ANY OF THE STEPS!!

  1. HOLD DOWN THE CTRL KEY AND PRESS  G .  WE CALL THIS CTRL-G.
     A MESSAGE WILL APPEAR AT THE BOTTOM OF THE PAGE WITH THE FILENAME AND THE
     POSITION IN THE FILE.  REMEMBER THE LINE NUMBER FOR STEP 3.

NOTE:  YOU MAY SEE THE CURSOR POSITION IN THE LOWER RIGHT CORNER OF THE SCREEN
       THIS HAPPENS WHEN THE 'RULER' OPTION IS SET (SEE  :HELP 'RULER'  )

  2. PRESS  G  TO MOVE YOU TO THE BOTTOM OF THE FILE.
     TYPE  GG  TO MOVE YOU TO THE START OF THE FILE.

  3. TYPE THE NUMBER OF THE LINE YOU WERE ON AND THEN  G .  THIS WILL
     RETURN YOU TO THE LINE YOU WERE ON WHEN YOU FIRST PRESSED CTRL-G.

  4. IF YOU FEEL CONFIDENT TO DO THIS, EXECUTE STEPS 1 THROUGH 3.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			LESSON 4.2: THE SEARCH COMMAND


     ** TYPE  /  FOLLOWED BY A PHRASE TO SEARCH FOR THE PHRASE. **

  1. IN NORMAL MODE TYPE THE  /  CHARACTER.  NOTICE THAT IT AND THE CURSOR
     APPEAR AT THE BOTTOM OF THE SCREEN AS WITH THE  :	COMMAND.

  2. NOW TYPE 'ERRROOR' <ENTER>.  THIS IS THE WORD YOU WANT TO SEARCH FOR.

  3. TO SEARCH FOR THE SAME PHRASE AGAIN, SIMPLY TYPE  N .
     TO SEARCH FOR THE SAME PHRASE IN THE OPPOSITE DIRECTION, TYPE  N .

  4. TO SEARCH FOR A PHRASE IN THE BACKWARD DIRECTION, USE  ?  INSTEAD OF  / .

  5. TO GO BACK TO WHERE YOU CAME FROM PRESS  CTRL-O  (KEEP CTRL DOWN WHILE
     PRESSING THE LETTER O).  REPEAT TO GO BACK FURTHER.  CTRL-I GOES FORWARD.

--->  "ERRROOR" IS NOT THE WAY TO SPELL ERROR;  ERRROOR IS AN ERROR.
NOTE: WHEN THE SEARCH REACHES THE END OF THE FILE IT WILL CONTINUE AT THE
      START, UNLESS THE 'WRAPSCAN' OPTION HAS BEEN RESET.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		   LESSON 4.3: MATCHING PARENTHESES SEARCH


	      ** TYPE  %  TO FIND A MATCHING ),], OR } . **

  1. PLACE THE CURSOR ON ANY (, [, OR { IN THE LINE BELOW MARKED --->.

  2. NOW TYPE THE  %  CHARACTER.

  3. THE CURSOR WILL MOVE TO THE MATCHING PARENTHESIS OR BRACKET.

  4. TYPE  %  TO MOVE THE CURSOR TO THE OTHER MATCHING BRACKET.

  5. MOVE THE CURSOR TO ANOTHER (,),[,],{ OR } AND SEE WHAT  %  DOES.

---> THIS ( IS A TEST LINE WITH ('S, ['S ] AND {'S } IN IT. ))


NOTE: THIS IS VERY USEFUL IN DEBUGGING A PROGRAM WITH UNMATCHED PARENTHESES!



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		      LESSON 4.4: THE SUBSTITUTE COMMAND


	** TYPE  :S/OLD/NEW/G  TO SUBSTITUTE 'NEW' FOR 'OLD'. **

  1. MOVE THE CURSOR TO THE LINE BELOW MARKED --->.

  2. TYPE  :S/THEE/THE <ENTER> .  NOTE THAT THIS COMMAND ONLY CHANGES THE
     FIRST OCCURRENCE OF "THEE" IN THE LINE.

  3. NOW TYPE  :S/THEE/THE/G .  ADDING THE  G  FLAG MEANS TO SUBSTITUTE
     GLOBALLY IN THE LINE, CHANGE ALL OCCURRENCES OF "THEE" IN THE LINE.

---> THEE BEST TIME TO SEE THEE FLOWERS IS IN THEE SPRING.

  4. TO CHANGE EVERY OCCURRENCE OF A CHARACTER STRING BETWEEN TWO LINES,
     TYPE   :#,#S/OLD/NEW/G    WHERE #,# ARE THE LINE NUMBERS OF THE RANGE
                               OF LINES WHERE THE SUBSTITUTION IS TO BE DONE.
     TYPE   :%S/OLD/NEW/G      TO CHANGE EVERY OCCURRENCE IN THE WHOLE FILE.
     TYPE   :%S/OLD/NEW/GC     TO FIND EVERY OCCURRENCE IN THE WHOLE FILE,
     			       WITH A PROMPT WHETHER TO SUBSTITUTE OR NOT.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			       LESSON 4 SUMMARY


  1. CTRL-G  DISPLAYS YOUR LOCATION IN THE FILE AND THE FILE STATUS.
             G  MOVES TO THE END OF THE FILE.
     NUMBER  G  MOVES TO THAT LINE NUMBER.
            GG  MOVES TO THE FIRST LINE.

  2. TYPING  /	FOLLOWED BY A PHRASE SEARCHES FORWARD FOR THE PHRASE.
     TYPING  ?	FOLLOWED BY A PHRASE SEARCHES BACKWARD FOR THE PHRASE.
     AFTER A SEARCH TYPE  N  TO FIND THE NEXT OCCURRENCE IN THE SAME DIRECTION
     OR  N  TO SEARCH IN THE OPPOSITE DIRECTION.
     CTRL-O TAKES YOU BACK TO OLDER POSITIONS, CTRL-I TO NEWER POSITIONS.

  3. TYPING  %	WHILE THE CURSOR IS ON A (,),[,],{, OR } GOES TO ITS MATCH.

  4. TO SUBSTITUTE NEW FOR THE FIRST OLD IN A LINE TYPE    :S/OLD/NEW
     TO SUBSTITUTE NEW FOR ALL 'OLD'S ON A LINE TYPE	   :S/OLD/NEW/G
     TO SUBSTITUTE PHRASES BETWEEN TWO LINE #'S TYPE	   :#,#S/OLD/NEW/G
     TO SUBSTITUTE ALL OCCURRENCES IN THE FILE TYPE	   :%S/OLD/NEW/G
     TO ASK FOR CONFIRMATION EACH TIME ADD 'C'		   :%S/OLD/NEW/GC

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		LESSON 5.1: HOW TO EXECUTE AN EXTERNAL COMMAND


   ** TYPE  :!	FOLLOWED BY AN EXTERNAL COMMAND TO EXECUTE THAT COMMAND. **

  1. TYPE THE FAMILIAR COMMAND	:  TO SET THE CURSOR AT THE BOTTOM OF THE
     SCREEN.  THIS ALLOWS YOU TO ENTER A COMMAND-LINE COMMAND.

  2. NOW TYPE THE  !  (EXCLAMATION POINT) CHARACTER.  THIS ALLOWS YOU TO
     EXECUTE ANY EXTERNAL SHELL COMMAND.

  3. AS AN EXAMPLE TYPE   LS   FOLLOWING THE ! AND THEN HIT <ENTER>.  THIS
     WILL SHOW YOU A LISTING OF YOUR DIRECTORY, JUST AS IF YOU WERE AT THE
     SHELL PROMPT.  OR USE  :!DIR  IF LS DOESN'T WORK.

NOTE:  IT IS POSSIBLE TO EXECUTE ANY EXTERNAL COMMAND THIS WAY, ALSO WITH
       ARGUMENTS.

NOTE:  ALL  :  COMMANDS MUST BE FINISHED BY HITTING <ENTER>
       FROM HERE ON WE WILL NOT ALWAYS MENTION IT.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		      LESSON 5.2: MORE ON WRITING FILES


     ** TO SAVE THE CHANGES MADE TO THE TEXT, TYPE  :W FILENAME. **

  1. TYPE  :!DIR  OR  :!LS  TO GET A LISTING OF YOUR DIRECTORY.
     YOU ALREADY KNOW YOU MUST HIT <ENTER> AFTER THIS.

  2. CHOOSE A FILENAME THAT DOES NOT EXIST YET, SUCH AS TEST.

  3. NOW TYPE:	 :W TEST   (WHERE TEST IS THE FILENAME YOU CHOSE.)

  4. THIS SAVES THE WHOLE FILE (THE VIM TUTOR) UNDER THE NAME TEST.
     TO VERIFY THIS, TYPE    :!DIR  OR  :!LS   AGAIN TO SEE YOUR DIRECTORY.

NOTE: IF YOU WERE TO EXIT VIM AND START IT AGAIN WITH  VIM TEST , THE FILE
      WOULD BE AN EXACT COPY OF THE TUTOR WHEN YOU SAVED IT.

  5. NOW REMOVE THE FILE BY TYPING (MS-DOS):    :!DEL TEST
				OR (UNIX):	:!RM TEST


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		    LESSON 5.3: SELECTING TEXT TO WRITE


	** TO SAVE PART OF THE FILE, TYPE  V  MOTION  :W FILENAME **

  1. MOVE THE CURSOR TO THIS LINE.

  2. PRESS  V  AND MOVE THE CURSOR TO THE FIFTH ITEM BELOW.  NOTICE THAT THE
     TEXT IS HIGHLIGHTED.

  3. PRESS THE  :  CHARACTER.  AT THE BOTTOM OF THE SCREEN  :'<,'> WILL APPEAR.

  4. TYPE  W TEST  , WHERE TEST IS A FILENAME THAT DOES NOT EXIST YET.  VERIFY
     THAT YOU SEE  :'<,'>W TEST  BEFORE YOU PRESS <ENTER>.

  5. VIM WILL WRITE THE SELECTED LINES TO THE FILE TEST.  USE  :!DIR  OR  :!LS
     TO SEE IT.  DO NOT REMOVE IT YET!  WE WILL USE IT IN THE NEXT LESSON.

NOTE:  PRESSING  V  STARTS VISUAL SELECTION.  YOU CAN MOVE THE CURSOR AROUND
       TO MAKE THE SELECTION BIGGER OR SMALLER.  THEN YOU CAN USE AN OPERATOR
       TO DO SOMETHING WITH THE TEXT.  FOR EXAMPLE,  D  DELETES THE TEXT.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		   LESSON 5.4: RETRIEVING AND MERGING FILES


       ** TO INSERT THE CONTENTS OF A FILE, TYPE  :R FILENAME  **

  1. PLACE THE CURSOR JUST ABOVE THIS LINE.

NOTE:  AFTER EXECUTING STEP 2 YOU WILL SEE TEXT FROM LESSON 5.3.  THEN MOVE
       DOWN TO SEE THIS LESSON AGAIN.

  2. NOW RETRIEVE YOUR TEST FILE USING THE COMMAND   :R TEST   WHERE TEST IS
     THE NAME OF THE FILE YOU USED.
     THE FILE YOU RETRIEVE IS PLACED BELOW THE CURSOR LINE.

  3. TO VERIFY THAT A FILE WAS RETRIEVED, CURSOR BACK AND NOTICE THAT THERE
     ARE NOW TWO COPIES OF LESSON 5.3, THE ORIGINAL AND THE FILE VERSION.

NOTE:  YOU CAN ALSO READ THE OUTPUT OF AN EXTERNAL COMMAND.  FOR EXAMPLE,
       :R !LS  READS THE OUTPUT OF THE LS COMMAND AND PUTS IT BELOW THE
       CURSOR.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			       LESSON 5 SUMMARY


  1.  :!COMMAND  EXECUTES AN EXTERNAL COMMAND.

      SOME USEFUL EXAMPLES ARE:
	 (MS-DOS)	  (UNIX)
	  :!DIR		   :!LS		   -  SHOWS A DIRECTORY LISTING.
	  :!DEL FILENAME   :!RM FILENAME   -  REMOVES FILE FILENAME.

  2.  :W FILENAME  WRITES THE CURRENT VIM FILE TO DISK WITH NAME FILENAME.

  3.  V  MOTION  :W FILENAME  SAVES THE VISUALLY SELECTED LINES IN FILE
      FILENAME.

  4.  :R FILENAME  RETRIEVES DISK FILE FILENAME AND PUTS IT BELOW THE
      CURSOR POSITION.

  5.  :R !DIR  READS THE OUTPUT OF THE DIR COMMAND AND PUTS IT BELOW THE
      CURSOR POSITION.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			 LESSON 6.1: THE OPEN COMMAND


 ** TYPE  O  TO OPEN A LINE BELOW THE CURSOR AND PLACE YOU IN INSERT MODE. **

  1. MOVE THE CURSOR TO THE LINE BELOW MARKED --->.

  2. TYPE THE LOWERCASE LETTER  O  TO OPEN UP A LINE BELOW THE CURSOR AND PLACE
     YOU IN INSERT MODE.

  3. NOW TYPE SOME TEXT AND PRESS <ESC> TO EXIT INSERT MODE.

---> AFTER TYPING  O  THE CURSOR IS PLACED ON THE OPEN LINE IN INSERT MODE.

  4. TO OPEN UP A LINE ABOVE THE CURSOR, SIMPLY TYPE A CAPITAL	O , RATHER
     THAN A LOWERCASE  O.  TRY THIS ON THE LINE BELOW.

---> OPEN UP A LINE ABOVE THIS BY TYPING O WHILE THE CURSOR IS ON THIS LINE.




~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			LESSON 6.2: THE APPEND COMMAND


	     ** TYPE  A  TO INSERT TEXT AFTER THE CURSOR. **

  1. MOVE THE CURSOR TO THE START OF THE LINE BELOW MARKED --->.
  
  2. PRESS  E  UNTIL THE CURSOR IS ON THE END OF  LI .

  3. TYPE AN  A  (LOWERCASE) TO APPEND TEXT AFTER THE CURSOR.

  4. COMPLETE THE WORD LIKE THE LINE BELOW IT.  PRESS <ESC> TO EXIT INSERT
     MODE.

  5. USE  E  TO MOVE TO THE NEXT INCOMPLETE WORD AND REPEAT STEPS 3 AND 4.
  
---> THIS LI WILL ALLOW YOU TO PRACT APPENDI TEXT TO A LINE.
---> THIS LINE WILL ALLOW YOU TO PRACTICE APPENDING TEXT TO A LINE.

NOTE:  A, I AND A ALL GO TO THE SAME INSERT MODE, THE ONLY DIFFERENCE IS WHERE
       THE CHARACTERS ARE INSERTED.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		    LESSON 6.3: ANOTHER WAY TO REPLACE


      ** TYPE A CAPITAL  R  TO REPLACE MORE THAN ONE CHARACTER. **

  1. MOVE THE CURSOR TO THE FIRST LINE BELOW MARKED --->.  MOVE THE CURSOR TO
     THE BEGINNING OF THE FIRST  XXX .

  2. NOW PRESS  R  AND TYPE THE NUMBER BELOW IT IN THE SECOND LINE, SO THAT IT
     REPLACES THE XXX .

  3. PRESS <ESC> TO LEAVE REPLACE MODE.  NOTICE THAT THE REST OF THE LINE
     REMAINS UNMODIFIED.

  4. REPEAT THE STEPS TO REPLACE THE REMAINING XXX.

---> ADDING 123 TO XXX GIVES YOU XXX.
---> ADDING 123 TO 456 GIVES YOU 579.

NOTE:  REPLACE MODE IS LIKE INSERT MODE, BUT EVERY TYPED CHARACTER DELETES AN
       EXISTING CHARACTER.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			LESSON 6.4: COPY AND PASTE TEXT


	  ** USE THE  Y  OPERATOR TO COPY TEXT AND  P  TO PASTE IT **

  1. GO TO THE LINE MARKED WITH ---> BELOW AND PLACE THE CURSOR AFTER "A)".
  
  2. START VISUAL MODE WITH  V  AND MOVE THE CURSOR TO JUST BEFORE "FIRST".
  
  3. TYPE  Y  TO YANK (COPY) THE HIGHLIGHTED TEXT.

  4. MOVE THE CURSOR TO THE END OF THE NEXT LINE:  J$

  5. TYPE  P  TO PUT (PASTE) THE TEXT.  THEN TYPE:  A SECOND <ESC> .

  6. USE VISUAL MODE TO SELECT " ITEM.", YANK IT WITH  Y , MOVE TO THE END OF
     THE NEXT LINE WITH  J$  AND PUT THE TEXT THERE WITH  P .

--->  A) THIS IS THE FIRST ITEM.
      B)

  NOTE: YOU CAN ALSO USE  Y  AS AN OPERATOR;  YW  YANKS ONE WORD.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			    LESSON 6.5: SET OPTION


	  ** SET AN OPTION SO A SEARCH OR SUBSTITUTE IGNORES CASE **

  1. SEARCH FOR 'IGNORE' BY ENTERING:   /IGNORE  <ENTER>
     REPEAT SEVERAL TIMES BY PRESSING  N .

  2. SET THE 'IC' (IGNORE CASE) OPTION BY ENTERING:   :SET IC

  3. NOW SEARCH FOR 'IGNORE' AGAIN BY PRESSING  N
     NOTICE THAT IGNORE AND IGNORE ARE NOW ALSO FOUND.

  4. SET THE 'HLSEARCH' AND 'INCSEARCH' OPTIONS:  :SET HLS IS

  5. NOW TYPE THE SEARCH COMMAND AGAIN AND SEE WHAT HAPPENS:  /IGNORE <ENTER>

  6. TO DISABLE IGNORING CASE ENTER:  :SET NOIC

NOTE:  TO REMOVE THE HIGHLIGHTING OF MATCHES ENTER:   :NOHLSEARCH 
NOTE:  IF YOU WANT TO IGNORE CASE FOR JUST ONE SEARCH COMMAND, USE  \C
       IN THE PHRASE:  /IGNORE\C  <ENTER>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			       LESSON 6 SUMMARY

  1. TYPE  O  TO OPEN A LINE BELOW THE CURSOR AND START INSERT MODE.
     TYPE  O  TO OPEN A LINE ABOVE THE CURSOR.

  2. TYPE  A  TO INSERT TEXT AFTER THE CURSOR.
     TYPE  A  TO INSERT TEXT AFTER THE END OF THE LINE.

  3. THE  E  COMMAND MOVES TO THE END OF A WORD.

  4. THE  Y  OPERATOR YANKS (COPIES) TEXT,  P  PUTS (PASTES) IT.

  5. TYPING A CAPITAL  R  ENTERS REPLACE MODE UNTIL  <ESC>  IS PRESSED.

  6. TYPING ":SET XXX" SETS THE OPTION "XXX".  SOME OPTIONS ARE:
  	'IC' 'IGNORECASE'	IGNORE UPPER/LOWER CASE WHEN SEARCHING
	'IS' 'INCSEARCH'	SHOW PARTIAL MATCHES FOR A SEARCH PHRASE
	'HLS' 'HLSEARCH'	HIGHLIGHT ALL MATCHING PHRASES
     YOU CAN EITHER USE THE LONG OR THE SHORT OPTION NAME.

  7. PREPEND "NO" TO SWITCH AN OPTION OFF:   :SET NOIC

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		       LESSON 7.1: GETTING HELP


		      ** USE THE ON-LINE HELP SYSTEM **

  VIM HAS A COMPREHENSIVE ON-LINE HELP SYSTEM.  TO GET STARTED, TRY ONE OF
  THESE THREE:
	- PRESS THE <HELP> KEY (IF YOU HAVE ONE)
	- PRESS THE <F1> KEY (IF YOU HAVE ONE)
	- TYPE   :HELP <ENTER>

  READ THE TEXT IN THE HELP WINDOW TO FIND OUT HOW THE HELP WORKS.
  TYPE  CTRL-W CTRL-W   TO JUMP FROM ONE WINDOW TO ANOTHER.
  TYPE    :Q <ENTER>    TO CLOSE THE HELP WINDOW.

  YOU CAN FIND HELP ON JUST ABOUT ANY SUBJECT, BY GIVING AN ARGUMENT TO THE
  ":HELP" COMMAND.  TRY THESE (DON'T FORGET PRESSING <ENTER>):

	:HELP W
	:HELP C_CTRL-D
	:HELP INSERT-INDEX
	:HELP USER-MANUAL
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		      LESSON 7.2: CREATE A STARTUP SCRIPT


			  ** ENABLE VIM FEATURES **

  VIM HAS MANY MORE FEATURES THAN VI, BUT MOST OF THEM ARE DISABLED BY
  DEFAULT.  TO START USING MORE FEATURES YOU HAVE TO CREATE A "VIMRC" FILE.

  1. START EDITING THE "VIMRC" FILE.  THIS DEPENDS ON YOUR SYSTEM:
	:E ~/.VIMRC		FOR UNIX
	:E $VIM/_VIMRC		FOR MS-WINDOWS

  2. NOW READ THE EXAMPLE "VIMRC" FILE CONTENTS:
	:R $VIMRUNTIME/VIMRC_EXAMPLE.VIM

  3. WRITE THE FILE WITH:
	:W

  THE NEXT TIME YOU START VIM IT WILL USE SYNTAX HIGHLIGHTING.
  YOU CAN ADD ALL YOUR PREFERRED SETTINGS TO THIS "VIMRC" FILE.
  FOR MORE INFORMATION TYPE  :HELP VIMRC-INTRO

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			     LESSON 7.3: COMPLETION


	      ** COMMAND LINE COMPLETION WITH CTRL-D AND <TAB> **

  1. MAKE SURE VIM IS NOT IN COMPATIBLE MODE:  :SET NOCP

  2. LOOK WHAT FILES EXIST IN THE DIRECTORY:  :!LS   OR  :!DIR

  3. TYPE THE START OF A COMMAND:  :E

  4. PRESS  CTRL-D  AND VIM WILL SHOW A LIST OF COMMANDS THAT START WITH "E".

  5. PRESS <TAB>  AND VIM WILL COMPLETE THE COMMAND NAME TO ":EDIT".

  6. NOW ADD A SPACE AND THE START OF AN EXISTING FILE NAME:  :EDIT FIL

  7. PRESS <TAB>.  VIM WILL COMPLETE THE NAME (IF IT IS UNIQUE).

NOTE:  COMPLETION WORKS FOR MANY COMMANDS.  JUST TRY PRESSING CTRL-D AND
       <TAB>.  IT IS ESPECIALLY USEFUL FOR  :HELP .

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			       LESSON 7 SUMMARY


  1. TYPE  :HELP  OR PRESS <F1> OR <HELP>  TO OPEN A HELP WINDOW.

  2. TYPE  :HELP CMD  TO FIND HELP ON  CMD .

  3. TYPE  CTRL-W CTRL-W  TO JUMP TO ANOTHER WINDOW

  4. TYPE  :Q  TO CLOSE THE HELP WINDOW

  5. CREATE A VIMRC STARTUP SCRIPT TO KEEP YOUR PREFERRED SETTINGS.

  6. WHEN TYPING A  :  COMMAND, PRESS CTRL-D TO SEE POSSIBLE COMPLETIONS.
     PRESS <TAB> TO USE ONE COMPLETION.







~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  THIS CONCLUDES THE VIM TUTOR.  IT WAS INTENDED TO GIVE A BRIEF OVERVIEW OF
  THE VIM EDITOR, JUST ENOUGH TO ALLOW YOU TO USE THE EDITOR FAIRLY EASILY.
  IT IS FAR FROM COMPLETE AS VIM HAS MANY MANY MORE COMMANDS.  READ THE USER
  MANUAL NEXT: ":HELP USER-MANUAL".

  FOR FURTHER READING AND STUDYING, THIS BOOK IS RECOMMENDED:
	VIM - VI IMPROVED - BY STEVE OUALLINE
	PUBLISHER: NEW RIDERS
  THE FIRST BOOK COMPLETELY DEDICATED TO VIM.  ESPECIALLY USEFUL FOR BEGINNERS.
  THERE ARE MANY EXAMPLES AND PICTURES.
  SEE HTTP://ICCF-HOLLAND.ORG/CLICK5.HTML

  THIS BOOK IS OLDER AND MORE ABOUT VI THAN VIM, BUT ALSO RECOMMENDED:
	LEARNING THE VI EDITOR - BY LINDA LAMB
	PUBLISHER: O'REILLY & ASSOCIATES INC.
  IT IS A GOOD BOOK TO GET TO KNOW ALMOST ANYTHING YOU WANT TO DO WITH VI.
  THE SIXTH EDITION ALSO INCLUDES INFORMATION ON VIM.

  THIS TUTORIAL WAS WRITTEN BY MICHAEL C. PIERCE AND ROBERT K. WARE,
  COLORADO SCHOOL OF MINES USING IDEAS SUPPLIED BY CHARLES SMITH,
  COLORADO STATE UNIVERSITY.  E-MAIL: BWARE@MINES.COLORADO.EDU.

  MODIFIED FOR VIM BY BRAM MOOLENAAR.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ASSIGNMENT FOR HOMEWORK 1 IN ECE 111.

RESEARCH THE VIM VS EMACS ARGUMENT ONLINE.  WHICH PROGRAM DO YOU LIKE MORE, VIM OR EMACS?
WRITE ANSWER HERE


REASERCH THE TAB VS SPACE ARGUMENT ONLINE (THE TV SHOW SILICON VALLEY HIGHLIGHTED THIS IN JUNE 2016).  WHICH CONVENTION DO YOU PREFER?  
WRITE ANSWER HERE

Submit this .txt file to Canvas by the due date for homework 1.