# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|                
  config.vm.box = 'bento/ubuntu-18.04'    

  config.vm.network "private_network", ip: "192.168.100.11"
  config.vm.hostname = "ubuntu-client"         

  config.vm.provider "virtualbox" do |vb|
     vb.name = "ubuntu-client"              
     vb.cpus = 2                         
     vb.memory = "2048"                  
  end                                    

  # config.vm.synced_folder '.', '/script/', nfs: true


  # config.vm.provision "shell", path: "./install_elastic.sh"
  # config.vm.provision "shell", path: "./install_kibana.sh"

config.vm.provision "shell", inline: <<-SHELL

   sudo apt update -y
 
SHELL

end