# -*- mode: ruby -*-
# vi: set ft=ruby :



# Tạo máy ảo VirtualBox - CentOS 7 để chạy thử Varnish Cache
# cùng với Nginx, PHP-FPM
Vagrant.configure(2) do |config|                
  config.vm.box = 'centos/7'                  

  config.vm.network "private_network", ip: "192.168.10.56"  
  config.vm.hostname = "vanish"

  config.vm.synced_folder '.', '/scripts/' # Chia sẻ thư mục máy host và máy ảo

  config.vm.provider "virtualbox" do |vb|
     vb.name = "vanish"
     vb.cpus = 2
     vb.memory = "2048"
  end


config.vm.provision "shell", inline: <<-SHELL

    yum update -y

    # Tat SELinux cua CentOS
    setenforce 0
    sed -i --follow-symlinks 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux


    # Đổi root password thành 123 và cho phép login SSH qua root
    echo "123" | passwd --stdin root
    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    systemctl reload sshd

SHELL

end